### ISSUE TITLE
Grunt instructions instruct you to use a gulp plugin

### ISSUE THREAD

**Issue by timothymalcham** [Shopify/shopify-css-import#11]
> 3. Install gulp (globally) and gulp-cssimport
> ```
> npm install -g gulp
> npm install gulp-cssimport
> ```

Instead they should probably instruct you to use a [Grunt plugin](https://www.npmjs.com/package/grunt-shopify-sass)...?

**Comment by timothymalcham** [comment]
After looking into the code a bit more, I realized you use a gulp plugin with grunt. Maybe make this more clear? At first it just seems like a major typo / error in the code. Most of the time you don't mix or match gulp/grunt plugins, at least I don't, I suspect most users don't either?

**Comment by cshold** [comment]
I'll update the docs to make it more clear. I agree, mixing Grunt and Gulp is a bit... odd to say the least. That said, the Gulp plugin is the only way we've found to concatenate the stylesheets the way we wanted - that being based on the `@import` statement order rather than the file names alphabetically. We tried both ways and this really does make organizing styles much easier and reducing any potential Sass errors for variables/mixins being included too late in the file.
